services:
  web-server:
    build:
      context: ./web-server
    ports:
      - "3000:3000"
    volumes:
      - ./web-server:/usr/src/app
    environment:
      - NODE_ENV=production
      - NODE_OPTIONS=--openssl-legacy-provider

  api-server:
    build:
      context: ./api-server
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - NODE_OPTIONS=--openssl-legacy-provider

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: dockdash-swagger
    ports:
      - "8080:8080"
    environment:
      - URL=./swagger.yaml
    volumes:
      - ./swagger/swagger.yaml:/usr/share/nginx/html/swagger.yaml:ro
    depends_on:
      - api-server
