services:
  
  web-server:
    container_name: dockdash-web-server
    hostname: dockdash-web
    build:
      context: ./web-server
    image: dockdash-web-server:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NODE_OPTIONS=--openssl-legacy-provider
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    volumes:
      - ./web-server/logs:/usr/src/app/logs
    networks:
      - dockdash-net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  api-server:
    container_name: dockdash-api-server
    hostname: dockdash-api
    build:
      context: ./api-server
    image: dockdash-api-server:latest
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - NODE_OPTIONS=--openssl-legacy-provider
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    networks:
      - dockdash-net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: dockdash-swagger
    hostname: dockdash-swagger
    ports:
      - "8080:8080"
    environment:
      - URL=./swagger.yaml
    volumes:
      - ./swagger/swagger.yaml:/usr/share/nginx/html/swagger.yaml:ro
    depends_on:
      - api-server
      
networks:
  dockdash-net:
    driver: bridge
